import puppeteer from "puppeteer-core"
const b = await puppeteer.connect({ browserURL: "http://127.0.0.1:9222", defaultViewport: null })
const p = await b.newPage()
await p.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 })
await p.goto("http://localhost:5173",{waitUntil:"domcontentloaded"})
await new Promise(r=>setTimeout(r,3000))
const box = await p.evaluate(()=>{const el=document.querySelector('[style*="translate3d"]');const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})
await p.mouse.move(box.x+box.w/2, box.y+40); await new Promise(r=>setTimeout(r,250))
await p.mouse.click(box.x+box.w-40, box.y+24)
// wait until burst is mid-life (~fly 0.95s + ~0.4s into burst)
await new Promise(r=>setTimeout(r,1800))
await p.screenshot({ path:"shots/burst-clip2.png", clip:{x:0,y:700,width:180,height:200} })
console.log("clip saved")
b.disconnect()
